### ISSUE TITLE
Build botway client packages

### ISSUE THREAD

**Issue by abdfnx** [abdfnx/botway#9]
# Packages to build

- [x] `botway-rs` botway rust client package
- [x] `botway.js` botway nodejs client package
- [x] `botway.py` botway python client package
- [x] `botwaygo` botway go client package
- [x] `botwayrb` botway ruby client package
- [x] `denobot` botway deno client package

**Comment by david-tomson** [comment]
finally, good job @abdfnx , now I am going to build `botway docker` command 🐳
